
// DisClose
export const DISCLOSE_PUBLISH = 'DISCLOSE/PUBLISH';
export const DISCLOSE_UPLOAD = 'DISCLOSE/UPLOAD';
export const DISCLOSE_GETLIST = 'DISCLOSE/GETLIST';
export const DISCLOSE_LIKE = 'DISCLOSE/LIKE';
export const DISCLOSE_DELETEDISCLOSE = 'DISCLOSE/DELETEDISCLOSE';

export const DISCLOSE_GETDISCLOSEDETAIL = 'DISCLOSE/GETDISCLOSEDETAIL';
export const DISCLOSE_GETDISCLOSEDETAIL_FROM_CACHE = 'DISCLOSE/DISCLOSE_GETDISCLOSEDETAIL_FROM_CACHE';

export const DISCLOSE_GETDISCLOSECOMMENTS = 'DISCLOSE/GETDISCLOSECOMMENTS';
export const DISCLOSE_COMMENTDISCLOSE = 'DISCLOSE/COMMENTDISCLOSE';
export const DISCLOSE_LIKECOMMENT = 'DISCLOSE/LIKECOMMENT';
export const DISCLOSE_CANCEL_LIKECOMMENT = 'DISCLOSE/DISCLOSE_CANCEL_LIKECOMMENT';
export const DISCLOSE_DELETECOMMENT = 'DISCLOSE/DELETECOMMENT';
export const DISCLOSE_GETLISTBYUSERID = 'DISCLOSE/GETLISTBYUSERID';
export const DISCLOSE_MINE_LIST = 'DISCLOSE/DISCLOSE_MINE_LIST';


export const DISCLOSE_CACHE_LIST = 'DISCLOSE/DISCLOSE_CACHE_LIST';
export const DISCLOSE_LIST_LOADMORE = 'DISCLOSE/DISCLOSE_LIST_LOADMORE';
export const DISCLOSE_LIST_UNSHIFT = 'DISCLOSE/DISCLOSE_LIST_UNSHIFT';
export const DISCLOSE_LIST_REFRESH = 'DISCLOSE/DISCLOSE_LIST_REFRESH';
export const DISCLOSE_ITEM_CHANGE = 'DISCLOSE/DISCLOSE_ITEM_CHANGE';
export const DISCLOSE_CANCEL_LIKE = 'DISCLOSE/DISCLOSE_CANCEL_LIKE';

// 不喜欢某条
export const DISCLOSE_DISLIKE = 'DISCLOSE/DISCLOSE_DISLIKE';
// 不喜欢某用户
export const DISCLOSE_DISLIKE_USERID = 'DISCLOSE/DISCLOSE_DISLIKE_USERID';
// 删除某条
export const DISCLOSE_REMOVE_ITEM = 'DISCLOSE/DISCLOSE_REMOVE_ITEM';
// 举报
export const DISCLOSE_PEPORT = 'DISCLOSE/DISCLOSE_PEPORT';

