export const DISCLOSE_UPLOAD = 'DISCLOSE/UPLOAD';
export const DISCLOSE_GETLIST = 'DISCLOSE/GETLIST';
export const DISCLOSE_LIKE = 'DISCLOSE/LIKE';
export const DISCLOSE_CANCEL_LIKE = 'DISCLOSE/DISCLOSE_CANCEL_LIKE';
export const DISCLOSE_DELETEDISCLOSE = 'DISCLOSE/DELETEDISCLOSE';

export const AUTH_UPDATE_USER = 'AUTH/AUTH_UPDATE_USER';
