export const FEED_GETDETAIL = 'FEED/GETDETAIL';
export const FEED_GETCOMMENTLIST = 'FEED/GETCOMMENTLIST';
export const FEED_LIKE = 'FEED/LIKE';
export const FEED_LIST_CANCEL_LIKE = 'FEED/FEED_LIST_CANCEL_LIKE';
export const FEED_LIST_LIKE = 'FEED/LIST_LIKE';
export const FEED_COMMENT = 'FEED/COMMENT';
export const FEED_DELETE_COMMENT = 'FEED/DELETECOMMENT';
export const FEED_LIKE_COMMENT = 'FEED/LIKECOMMENT';
export const FEED_CANCEL_LIKE_COMMENT = 'FEED/FEED_CANCEL_LIKE_COMMENT';
export const FEED_PEPORT = 'FEED/FEED_PEPORT';

