//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// User
export const SET_USER_INFO = 'USER/SET_INFO';
export const CLEAR_USER_INFO = 'USER/CLEAR_INFO';

// APP
export const APP_INIT = 'APP/INIT';


// Auth
export const AUTH_REGISTER = 'AUTH/REGISTER';
export const AUTH_LOGIN = 'AUTH/LOGIN';
export const AUTH_LOGOUT = 'AUTH/LOGOUT';
export const AUTH_VERIFY = 'AUTH/VERIFY';
export const AUTH_RESEND = 'AUTH/RESEND';
export const AUTH_REFRESH = 'AUTH/AUTH_REFRESH';

// DisClose
export const DISCLOSE_PUBLISH = 'DISCLOSE/PUBLISH';
export const DISCLOSE_UPLOAD = 'DISCLOSE/UPLOAD';
export const DISCLOSE_GETLIST = 'DISCLOSE/GETLIST';
export const DISCLOSE_LIKE = 'DISCLOSE/LIKE';
export const DISCLOSE_DELETEDISCLOSE = 'DISCLOSE/DELETEDISCLOSE';
export const DISCLOSE_GETDISCLOSEDETAIL = 'DISCLOSE/GETDISCLOSEDETAIL';
export const DISCLOSE_GETDISCLOSECOMMENTS = 'DISCLOSE/GETDISCLOSECOMMENTS';
export const DISCLOSE_COMMENTDISCLOSE = 'DISCLOSE/COMMENTDISCLOSE';
export const DISCLOSE_LIKECOMMENT = 'DISCLOSE/LIKECOMMENT';
export const DISCLOSE_DELETECOMMENT = 'DISCLOSE/DELETECOMMENT';
export const DISCLOSE_GETLISTBYUSERID = 'DISCLOSE/GETLISTBYUSERID';

// Feed
export const FEED_GETLIST = 'FEED/GETLIST';
export const FEED_GETDETAIL = 'FEED/GETDETAIL';
export const FEED_SET_LIST = 'FEED/APPEND_LIST';
export const FEED_APPEND_LIST = 'FEED/APPEND_LIST';
export const FEED_REFRESH_LIST = 'FEED/REFRESH_LIST';
export const FEED_PREPEND_LIST = 'FEED/PREPEND_LIST';

export const FEED_GETCOMMENTLIST = 'FEED/GETCOMMENTLIST';
export const FEED_LIKE = 'FEED/LIKE';
export const FEED_COMMENT = 'FEED/COMMENT';
export const FEED_DELETE_COMMENT = 'FEED/DELETECOMMENT';
export const FEED_LIKE_COMMENT = 'FEED/LIKECOMMENT';


// userActions
export const USERACTION_GETACTION = 'USER/GETACTION';
export const USERACTION_UPDATE = 'USERACTION/UPDATE';
