//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// User
export const SET_USER_INFO = 'USER/SET_INFO';
export const CLEAR_USER_INFO = 'USER/CLEAR_INFO';

// 某个用户不感兴趣的内容的id，下次不再展示该内容
export const APPEND_DISLIKE_FEEDID = 'USER/APPEND_DISLIKE_FEEDID';
export const APPEND_DISLIKE_DISCLOSEID = 'USER/APPEND_DISLIKE_DISCLOSEID';
export const APPEND_DISLIKE_USERID = 'USER/APPEND_DISLIKE_USERID';
export const APPEND_DISLIKE_FEED_USERID = 'USER/APPEND_DISLIKE_FEED_USERID';


// APP
export const APP_INIT = 'APP/INIT';


// USER AUTH 相关
export const AUTH_LOGOUT = 'AUTH/LOGOUT';
export const AUTH_UPDATE_USER = 'AUTH/AUTH_UPDATE_USER';
export const AUTH_SEND_SMD = 'AUTH/AUTH_SEND_SMD';
export const AUTH_LOGIN_OR_REG = 'AUTH/AUTH_LOGIN_OR_REG';
export const AUTH_UPLOAD = 'AUTH/AUTH_UPLOAD';


// DisClose
export const DISCLOSE_PUBLISH = 'DISCLOSE/PUBLISH';
export const DISCLOSE_UPLOAD = 'DISCLOSE/UPLOAD';
export const DISCLOSE_GETLIST = 'DISCLOSE/GETLIST';
export const DISCLOSE_LIKE = 'DISCLOSE/LIKE';
export const DISCLOSE_DELETEDISCLOSE = 'DISCLOSE/DELETEDISCLOSE';

export const DISCLOSE_GETDISCLOSEDETAIL = 'DISCLOSE/GETDISCLOSEDETAIL';
export const DISCLOSE_GETDISCLOSEDETAIL_FROM_CACHE = 'DISCLOSE/DISCLOSE_GETDISCLOSEDETAIL_FROM_CACHE';

export const DISCLOSE_GETDISCLOSECOMMENTS = 'DISCLOSE/GETDISCLOSECOMMENTS';
export const DISCLOSE_COMMENTDISCLOSE = 'DISCLOSE/COMMENTDISCLOSE';
export const DISCLOSE_LIKECOMMENT = 'DISCLOSE/LIKECOMMENT';
export const DISCLOSE_CANCEL_LIKECOMMENT = 'DISCLOSE/DISCLOSE_CANCEL_LIKECOMMENT';
export const DISCLOSE_DELETECOMMENT = 'DISCLOSE/DELETECOMMENT';
export const DISCLOSE_GETLISTBYUSERID = 'DISCLOSE/GETLISTBYUSERID';
export const DISCLOSE_MINE_LIST = 'DISCLOSE/DISCLOSE_MINE_LIST';


export const DISCLOSE_CACHE_LIST = 'DISCLOSE/DISCLOSE_CACHE_LIST';
export const DISCLOSE_LIST_LOADMORE = 'DISCLOSE/DISCLOSE_LIST_LOADMORE';
export const DISCLOSE_LIST_UNSHIFT = 'DISCLOSE/DISCLOSE_LIST_UNSHIFT';
export const DISCLOSE_LIST_REFRESH = 'DISCLOSE/DISCLOSE_LIST_REFRESH';
export const DISCLOSE_ITEM_CHANGE = 'DISCLOSE/DISCLOSE_ITEM_CHANGE';
export const DISCLOSE_CANCEL_LIKE = 'DISCLOSE/DISCLOSE_CANCEL_LIKE';
// 不喜欢某条
export const DISCLOSE_DISLIKE = 'DISCLOSE/DISCLOSE_DISLIKE';
// 不喜欢某用户
export const DISCLOSE_DISLIKE_USERID = 'DISCLOSE/DISCLOSE_DISLIKE_USERID';
// 删除某条
export const DISCLOSE_REMOVE_ITEM = 'DISCLOSE/DISCLOSE_REMOVE_ITEM';
// 举报
export const DISCLOSE_PEPORT = 'DISCLOSE/DISCLOSE_PEPORT';


// Feed
export const FEED_GETLIST = 'FEED/GETLIST';
export const FEED_GETCACHELIST = 'FEED/GETCACHELIST';

export const FEED_GETDETAIL = 'FEED/GETDETAIL';
export const FEED_GETDETAIL_FROM_CACHE = 'FEED/FEED_GETDETAIL_FROM_CACHE';

export const FEED_SET_LIST = 'FEED/APPEND_LIST';
export const FEED_APPEND_LIST = 'FEED/APPEND_LIST';
export const FEED_REFRESH_LIST = 'FEED/REFRESH_LIST';

// 屏蔽某用户
export const FEED_DISLIKE_USER = 'FEED/REFRESH_LIST';


// 他人主页列表
export const FEED_APPEND_OTHERHOME_LIST = 'FEED/FEED_APPEND_OTHERHOME_LIST';
export const FEED_PREPEND_OTHERHOME_LIST = 'FEED/FEED_PREPEND_OTHERHOME_LIST';


export const FEED_PREPEND_LIST = 'FEED/PREPEND_LIST';
export const FEED_LIST_LIKE = 'FEED/LIST_LIKE';
export const FEED_LIST_DISLIKE = 'FEED/FEED_LIST_DISLIKE';
export const FEED_LIST_CANCEL_LIKE = 'FEED/FEED_LIST_CANCEL_LIKE';
export const FEED_ITEM_CHANGE = 'FEED/FEED_ITEM_CHANGE';
export const FEED_ROMEVE_ITEM = 'FEED/FEED_ROMEVE_ITEM';
export const FEED_ROMEVE_ITEM_BYUSERID = 'FEED/FEED_ROMEVE_ITEM_BYUSERID';


export const FEED_GETCOMMENTLIST = 'FEED/GETCOMMENTLIST';
export const FEED_LIKE = 'FEED/LIKE';

export const FEED_COMMENT = 'FEED/COMMENT';
export const FEED_DELETE_COMMENT = 'FEED/DELETECOMMENT';
export const FEED_LIKE_COMMENT = 'FEED/LIKECOMMENT';
export const FEED_CANCEL_LIKE_COMMENT = 'FEED/FEED_CANCEL_LIKE_COMMENT';
export const FEED_LIST_BYUSERID = 'FEED/LISTBYUSERID';

export const FEED_PEPORT = 'FEED/FEED_PEPORT';


// userActions
export const USERACTION_GETACTION = 'USER/GETACTION';
export const USERACTION_UPDATE = 'USERACTION/UPDATE';
export const USERACTION_REPORT = 'USERACTION/REPORT';


// cache
export const CACHE_SETLIST = 'CACHE/SETLIST';

// 行情
export const MARKET_GET_LIST = 'MARKET/MARKET_GET_LIST';
export const MARKET_SET_LIST = 'MARKET/MARKET_SET_LIST'
export const MARKET_APPEND_LIST = 'MARKET/MARKET_APPEND_LIST'
export const MARKET_GET_LIST_BY_MINE_ID = 'MARKET/MARKET_GET_LIST_BY_MINE_ID'
export const MARKET_UPDATE_MINE_DATA = 'MARKET/MARKET_UPDATE_MINE_DATA'

export const MAARKET_APPEND_DISCUSS_LIST = 'MARKET/MAARKET_APPEND_DISCUSS_LIST'
export const MARKET_SET_MARKET_PAIR_LIST_BY_COINID = 'MARKET/MARKET_SET_MARKET_PAIR_LIST_BY_COINID'
export const MARKET_APPEND_MARKET_PAIR_LIST_BY_COINID = 'MARKET/MARKET_APPEND_MARKET_PAIR_LIST_BY_COINID'
export const MARKET_INIT_SEARCH_LIST = 'MARKET/MARKET_INIT_SEARCH_LIST'
export const MARKET_GET_AVG_PRICE_DATA = 'MARKET/MARKET_GET_AVG_PRICE_DATA'
export const MARKET_SET_AVG_PRICE_DATA = 'MARKET/MARKET_SET_AVG_PRICE_DATA'

export const MARKET_GET_DISCUSS_DETAIL = 'MARKET/MARKET_GET_DISCUSS_DETAIL'
export const MARKET_SET_DISCUSS_DETAIL = 'MARKET/MARKET_SET_DISCUSS_DETAIL'
export const MARKET_DISCUSS_COIN = 'MARKET/MARKET_DISCUSS_COIN'
export const MARKET_DISCUSS_REPLY = 'MARKET/MARKET_DISCUSS_REPLY'

export const MARKET_LIKE_DISCUSS = 'MARKET/MARKET_LIKE_DISCUSS'
export const MARKET_CALCEL_LIKE_DISCUSS = 'MARKET/MARKET_CALCEL_LIKE_DISCUSS'
export const MARKET_DELETE_DISCUSS = 'MARKET/MARKET_DELETE_DISCUSS'

export const MARKET_SORT_LIST = 'MARKET/MARKET_SORT_LIST';
export const MARKET_ADD_COLLECTION = 'MARKET/MARKET_ADD_COLLECTION';
export const MARKET_REMOVE_COLLECTION = 'MARKET/MARKET_REMOVE_COLLECTION';

//行情详情
export const MARKET_GET_COIN_DETAIL = 'MARKET/MARKET_GET_COIN_DETAIL'
export const MARKET_SET_COIN_DETAIL = 'MARKET/MARKET_SET_COIN_DETAIL'
export const MARKET_GET_DISCUSS_LIST = 'MARKET/MARKET_GET_DISCUSS_LIST'
export const MARKET_SET_DISCUSS_LIST = 'MARKET/MARKET_SET_DISCUSS_LIST'
export const MARKET_GET_MARKET_PAIR_LIST_BY_COINID = 'MARKET/MARKET_GET_MARKET_PAIR_LIST_BY_COINID'
export const MARKET_INIT_DISCUSS_DETAIL = 'MARKET/MARKET_INIT_DISCUSS_DETAIL'


